version: "3.1"

services:
  surreal:
    build:
      context: ./services/surreal
    restart: unless-stopped
    container_name: surreal
    environment:
      - SURREAL_USER=root
      - SURREAL_PASS=root
    volumes:
      - surreal_data:/data
    ports:
      - 8080:8080

volumes:
  surreal_data: