version: "3.1"

services:
  surreal:
    image: surrealdb/surrealdb:1.0.0-beta.9-20230402
    command: start --bind 0.0.0.0:8080 --user root --pass root --log debug file://data/srdb.db
    restart: unless-stopped
    container_name: surreal
    volumes:
      - ./data:/data
      - ./schema.surql/:/schema.surql
    ports:
      - 8080:8080
