version: "3.1"

services:
  surreal:
    build:
      context: ./services/surreal
    restart: unless-stopped
    container_name: surreal
    env_file:
      - ./.env.local
    volumes:
      - surreal_data:/data
    ports:
      - 8080:8080

  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    entrypoint: yarn workspace @nimblerp/web dev
    restart: unless-stopped
    working_dir: /workspace
    env_file:
      - ./.env.local
    volumes:
      - ./apps/web/src:/workspace/apps/web/src
    ports:
      - 3000:3000
    depends_on:
      - surreal

volumes:
  surreal_data: