version: "3.1"

services:
  surreal:
    build:
      context: .
      dockerfile: services/surreal/Dockerfile
    command: start --bind 0.0.0.0:8080 --auth --user root --pass root --log debug file://data/srdb.db
    restart: unless-stopped
    container_name: surreal
    volumes:
      - ./data:/data
      - ./schema.surql/:/schema.surql
    ports:
      - 8080:8080
