version: "3.1"

services:
  surreal:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    command: start --bind 0.0.0.0:8080 --user root --pass root --log debug file://data/srdb.db
    # environment:
    #   - SURREAL_USER=root
    #   - SURREAL_PASSWORD=root
    container_name: surreal
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
