providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1716249803'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['install']
cmds = [
    'bunx convex deploy --preview-create --cmd-url-env-var-name NEXT_PUBLIC_CONVEX_URL --cmd "bun run build"',
]
cacheDirectories = ['.next/cache', 'node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['bun i --no-save']
cacheDirectories = ['/root/.bun']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = ['nodejs_18', 'bun', 'git']
nixOverlays = [
    'https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz',
]
nixpkgsArchive = 'bdd2f439c62aa0b8aa97f5c784a965c23f968fe6'

[start]
cmd = 'bun run start'
