/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as actions from "../actions.js";
import type * as bookings from "../bookings.js";
import type * as countries from "../countries.js";
import type * as crons from "../crons.js";
import type * as customers from "../customers.js";
import type * as emails from "../emails.js";
import type * as eventTypes from "../eventTypes.js";
import type * as events from "../events.js";
import type * as http from "../http.js";
import type * as invoices from "../invoices.js";
import type * as items from "../items.js";
import type * as notifications from "../notifications.js";
import type * as settings from "../settings.js";
import type * as stats from "../stats.js";
import type * as storage from "../storage.js";
import type * as stripe_checkout from "../stripe/checkout.js";
import type * as stripe_constants from "../stripe/constants.js";
import type * as stripe_customers from "../stripe/customers.js";
import type * as stripe_invoices from "../stripe/invoices.js";
import type * as stripe_subscriptions from "../stripe/subscriptions.js";
import type * as stripe_webhooks from "../stripe/webhooks.js";
import type * as tests from "../tests.js";
import type * as utils from "../utils.js";
import type * as workflows from "../workflows.js";
import type * as workspaces from "../workspaces.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  actions: typeof actions;
  bookings: typeof bookings;
  countries: typeof countries;
  crons: typeof crons;
  customers: typeof customers;
  emails: typeof emails;
  eventTypes: typeof eventTypes;
  events: typeof events;
  http: typeof http;
  invoices: typeof invoices;
  items: typeof items;
  notifications: typeof notifications;
  settings: typeof settings;
  stats: typeof stats;
  storage: typeof storage;
  "stripe/checkout": typeof stripe_checkout;
  "stripe/constants": typeof stripe_constants;
  "stripe/customers": typeof stripe_customers;
  "stripe/invoices": typeof stripe_invoices;
  "stripe/subscriptions": typeof stripe_subscriptions;
  "stripe/webhooks": typeof stripe_webhooks;
  tests: typeof tests;
  utils: typeof utils;
  workflows: typeof workflows;
  workspaces: typeof workspaces;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
