/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as bookings from "../bookings.js";
import type * as cloudinary from "../cloudinary.js";
import type * as countries from "../countries.js";
import type * as customers from "../customers.js";
import type * as eventTypes from "../eventTypes.js";
import type * as events from "../events.js";
import type * as invoices from "../invoices.js";
import type * as items from "../items.js";
import type * as settings from "../settings.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  bookings: typeof bookings;
  cloudinary: typeof cloudinary;
  countries: typeof countries;
  customers: typeof customers;
  eventTypes: typeof eventTypes;
  events: typeof events;
  invoices: typeof invoices;
  items: typeof items;
  settings: typeof settings;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
